######################################################################
# Automatically generated by qmake (2.01a) mer. avr. 13 13:10:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += classesbase.h combat.h
SOURCES += classesbase.cpp combat.cpp main.cpp
